import { AppProps } from 'next/app'
import Head from 'next/head'

import { CartContextProvider } from '@/widgets/cart/context/CartContext'

export const EntryPoint = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>
          Онлайн-сервис по мониторингу и уничтожению опасных астероидов
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CartContextProvider>
        <Component {...pageProps} />
      </CartContextProvider>
    </>
  )
}
